version: '3.4'

services:
  api:
    build:
      context: .
      target: 'dev'
      dockerfile: docker/api/Dockerfile
    container_name: '${APP_NAME}-api'
    hostname: api
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - '.:/var/www:cached'
      - '${APP_PATH_TO_DIR:-./}docker/api/conf/php.ini:/usr/local/etc/php/conf.d/user.ini'
    env_file:
      - .env
  nginx:
    image: nginx:1.17-alpine
    container_name: '${APP_NAME}-nginx'
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - '${APP_PATH_TO_DIR:-./}docker/nginx/conf/server.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${NGINX_PORT:-80}:80'
  db:
#    image: mariadb:10.4
    image: 'mysql/mysql-server:8.0'
    container_name: '${APP_NAME}-db'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - db-data:/var/lib/mysql:delegated
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_USER=root'
volumes:
  db-data:
  state:
    driver: local